### ISSUE TITLE
searchRead returns page not found error

### ISSUE THREAD

**Issue by edwingonzales** [hparfr/odoo-ionic-sample#4]
Login works but running searchRead returns 

{title: "page_not_found", message: "HTTP Error", fullTrace: Object}

Please help. Thanks.

**Comment by edwingonzales** [comment]
I'm getting this in my Odoo Server log

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 599, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 1552, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/usr/lib/python2.7/dist-packages/werkzeug/routing.py", line 1433, in match
    raise NotFound()
NotFound: 404: Not Found
